image: node

stages: 
  - deploy

compile: 
  stage: deploy
  script:
    - echo "Build starting"
    - npm build
    - npm i firebase-tools
    - npm i firebase
    - echo "deploy starting"
    - firebase deploy