image: node

stages: 
  - deploy

compile: 
  stage: deploy
  script:
    - echo "Build starting"
    - npm build
    - npm i -g firebase-tools
    - npm i -g firebase
    - echo "deploy starting"
    - firebase deploy